# Generated by Django 4.0.2 on 2026-09-15 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'verbose_name': 'Filho',
                'verbose_name_plural': 'Filhos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='DespesaFilho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveIntegerField(default=2026)),
                ('mes', models.PositiveSmallIntegerField(choices=[(1, 'Janeiro'), (2, 'Fevereiro'), (3, 'Março'), (4, 'Abril'), (5, 'Maio'), (6, 'Junho'), (7, 'Julho'), (8, 'Agosto'), (9, 'Setembro'), (10, 'Outubro'), (11, 'Novembro'), (12, 'Dezembro')])),
                ('descricao', models.CharField(max_length=120)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('fechado', 'Fechado'), ('cartao', 'Cartão')], default='aberto', max_length=20)),
                ('filho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despesas', to='filhos.filho')),
            ],
            options={
                'verbose_name': 'Despesa do filho',
                'verbose_name_plural': 'Despesas dos filhos',
                'ordering': ['ano', 'mes', 'filho__nome', 'descricao'],
            },
        ),
    ]
