# Generated by Django 4.0.2 on 2026-09-15 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cartoes', '0001_initial'),
        ('filhos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesafilho',
            name='item_fatura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despesas_filhos', to='cartoes.itemfatura'),
        ),
    ]
