# Generated by Django 4.0.2 on 2026-09-22 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filhos', '0002_despesafilho_item_fatura'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesafilho',
            name='dia_vencimento',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Dia do mês em que vence (1 a 31).', null=True, verbose_name='Dia de vencimento'),
        ),
        migrations.AddField(
            model_name='despesafilho',
            name='recorrente',
            field=models.BooleanField(default=False, help_text='Permite gerar automaticamente no mês seguinte.', verbose_name='Lançamento recorrente'),
        ),
        migrations.AlterField(
            model_name='despesafilho',
            name='status',
            field=models.CharField(choices=[('aberto', 'A pagar'), ('fechado', 'Pago'), ('cartao', 'No cartão')], default='aberto', max_length=20),
        ),
    ]
