# Generated by Django 4.0.2 on 2026-09-15 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consorcio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('grupo', models.CharField(blank=True, max_length=80)),
                ('total_parcelas', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Consórcio',
                'verbose_name_plural': 'Consórcios',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ParcelaConsorcio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveIntegerField(default=2026)),
                ('mes', models.PositiveSmallIntegerField(choices=[(1, 'Janeiro'), (2, 'Fevereiro'), (3, 'Março'), (4, 'Abril'), (5, 'Maio'), (6, 'Junho'), (7, 'Julho'), (8, 'Agosto'), (9, 'Setembro'), (10, 'Outubro'), (11, 'Novembro'), (12, 'Dezembro')])),
                ('numero_parcela', models.PositiveIntegerField(blank=True, null=True)),
                ('rotulo_parcela', models.CharField(blank=True, max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('fechado', 'Fechado')], default='aberto', max_length=20)),
                ('consorcio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='imoveis_transporte.consorcio')),
            ],
            options={
                'verbose_name': 'Parcela de consórcio',
                'verbose_name_plural': 'Parcelas de consórcio',
                'ordering': ['ano', 'mes', 'consorcio__nome'],
                'unique_together': {('consorcio', 'ano', 'mes')},
            },
        ),
    ]
