# Generated by Django 4.0.2 on 2026-09-22 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis_transporte', '0003_parcelaconsorcio_dia_vencimento_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parcelaconsorcio',
            options={'ordering': ['ano', 'mes', 'consorcio__nome', 'numero_parcela', 'id'], 'verbose_name': 'Parcela de consórcio', 'verbose_name_plural': 'Parcelas de consórcio'},
        ),
        migrations.AlterUniqueTogether(
            name='parcelaconsorcio',
            unique_together=set(),
        ),
    ]
