# Generated by Django 4.0.2 on 2026-09-22 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartao',
            name='dia_vencimento',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Dia do mês em que a fatura vence (1 a 31).', null=True, verbose_name='Dia de vencimento'),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='status',
            field=models.CharField(choices=[('aberto', 'A pagar'), ('fechado', 'Paga')], default='aberto', max_length=20),
        ),
    ]
