# Generated by Django 4.0.2 on 2026-09-24 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartoes', '0002_cartao_dia_vencimento_alter_fatura_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemfatura',
            name='parcela_atual',
            field=models.PositiveSmallIntegerField(default=1, help_text='Número desta parcela (ex.: 2 de 6).', verbose_name='Parcela atual'),
        ),
        migrations.AddField(
            model_name='itemfatura',
            name='quantidade_parcelas',
            field=models.PositiveSmallIntegerField(default=1, help_text='Total de parcelas da compra. Use 1 se for à vista.', verbose_name='Qtd. parcelas'),
        ),
    ]
