# Generated by Django 4.0.2 on 2026-09-15 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveIntegerField(default=2026)),
                ('mes', models.PositiveSmallIntegerField(choices=[(1, 'Janeiro'), (2, 'Fevereiro'), (3, 'Março'), (4, 'Abril'), (5, 'Maio'), (6, 'Junho'), (7, 'Julho'), (8, 'Agosto'), (9, 'Setembro'), (10, 'Outubro'), (11, 'Novembro'), (12, 'Dezembro')])),
                ('fonte', models.CharField(choices=[('salario_aline', 'Salário Aline'), ('salario_luiz', 'Salário Luiz'), ('mesada_vovo', 'Mesada Vovô'), ('outros', 'Outros')], max_length=30)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('observacao', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Receita',
                'verbose_name_plural': 'Receitas',
                'ordering': ['ano', 'mes', 'fonte'],
            },
        ),
    ]
