# Generated by Django 4.0.2 on 2026-09-22 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='dia_vencimento',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Dia do mês em que o valor deve entrar (1 a 31).', null=True, verbose_name='Dia previsto'),
        ),
        migrations.AddField(
            model_name='receita',
            name='recorrente',
            field=models.BooleanField(default=False, help_text='Permite gerar automaticamente no mês seguinte.', verbose_name='Lançamento recorrente'),
        ),
        migrations.AddField(
            model_name='receita',
            name='status',
            field=models.CharField(choices=[('previsto', 'Previsto'), ('recebido', 'Recebido')], default='recebido', max_length=20),
        ),
    ]
