# Generated by Django 4.0.2 on 2026-09-22 18:31

from django.db import migrations, models


def popular_anos(apps, schema_editor):
    Ano = apps.get_model('inicio', 'Ano')
    for numero in (2025, 2026, 2027, 2028):
        Ano.objects.get_or_create(numero=numero, defaults={'ativo': True})


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_receita_dia_vencimento_receita_recorrente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(unique=True, verbose_name='Ano')),
                ('ativo', models.BooleanField(default=True, help_text='Se marcado, o ano aparece no seletor do sistema.')),
            ],
            options={
                'verbose_name': 'Ano',
                'verbose_name_plural': 'Anos',
                'ordering': ['numero'],
            },
        ),
        migrations.RunPython(popular_anos, migrations.RunPython.noop),
    ]
